apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c-deployment
  labels:
    app: service-c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c-deployment
  template:
    metadata:
      labels:
        app: service-c-deployment
    spec:
      containers:
      - name: service-c-deployment
        image: josephrechdiner/service-c:v5
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST
          value: "mysql-0.mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "weather_db"